---
- name: Set up Vagrant VM with Docker and Web Application
  hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - common-tasks
    - frontend-setup
    - backend-setup

  tasks:
    - name: Clone the application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
      tags: app_setup

