---
# tasks file for common-tasks

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install Docker Python module
  pip:
    name: docker

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
